"use strict";

process.env.NODE_ENV = "test";

const assert = require("assert");
const contract = require("../src/contracts/flutterMobileResponseContract");

const FLUTTER_BASELINE = "Basic-Diet/mobile_app@6e1be0b38272160bc377cedf391cf082d0f2abfa";
const subscriptionId = "64c000000000000000000001";
const dayId = "64c000000000000000000002";
const productId = "64c000000000000000000003";
const addonPlanId = "64c000000000000000000004";
const bucketId = "64c000000000000000000005";
const requestId = "64c000000000000000000006";
const businessDate = "2026-07-22";

const allowance = {
  entitlementIndex: 0,
  entitlementKey: `juice:${addonPlanId}`,
  addonPlanId,
  addonPlanName: "اشتراك عصير",
  displayCategory: "juice",
  allowanceCategory: "juice",
  includedTotalQty: 10,
  consumedQty: 3,
  reservedQty: 2,
  remainingIncludedQty: 5,
  overageUnitPriceHalala: 500,
  currency: "SAR",
  choicesCount: 1,
  menuProductIds: [productId],
  source: "subscription",
  maxPerDay: 5,
  defaultDailyQty: 1,
  walletRemainingQty: 5,
  maximumSpendableFromWallet: 5,
};

const mealBalance = {
  totalMeals: 52,
  remainingMeals: 48,
  consumedMeals: 2,
  canConsumeNow: true,
  maxConsumableMealsNow: 48,
  mealBalancePolicy: "TOTAL_BALANCE_WITHIN_VALIDITY",
  dailyMealLimitEnforced: false,
  dailyMealsDefault: 2,
};

const overview = {
  status: true,
  data: {
    _id: subscriptionId,
    businessDate,
    status: "active",
    startDate: "2026-07-01",
    endDate: "2026-08-31",
    totalMeals: 52,
    remainingMeals: 48,
    premiumRemaining: 4,
    addonSubscriptions: [{ addonId: addonPlanId, category: "juice", includedCount: 10, maxPerDay: 1, status: "active" }],
    addonBalances: [{
      addonPlanId,
      addonId: addonPlanId,
      name: { ar: "اشتراك عصير", en: "Juice subscription" },
      category: "juice",
      purchasedDailyQty: 1,
      includedTotalQty: 10,
      purchasedQty: 10,
      consumedQty: 3,
      reservedQty: 2,
      remainingQty: 5,
      currency: "SAR",
    }],
    addonSubscriptionAllowances: [allowance],
    addonCategoryAllowances: [{
      category: "juice",
      includedTotalQty: 10,
      consumedQty: 3,
      reservedQty: 2,
      remainingIncludedQty: 5,
      overageUnitPriceHalala: 500,
      currency: "SAR",
    }],
    selectedMealsPerDay: 2,
    deliveryMode: "pickup",
    premiumSummary: [],
    addonsSummary: [],
    statusLabel: "نشط",
    deliveryModeLabel: "استلام من الفرع",
    deliveryWindowLegacy: "",
    pickupLocationId: "main",
    validityEndDate: "2026-08-31",
    skipDaysUsed: 0,
    skipDaysLimit: 5,
    remainingSkipDays: 5,
    meta: { testScenario: "flutter_contract" },
    contract: { isCanonical: true, isGrandfathered: false, version: "v4" },
    pickupPreparation: {
      flowStatus: "available",
      reason: null,
      buttonLabel: "تحضير",
      message: "",
      canRequestPrepare: true,
      canBePrepared: true,
      planningReady: true,
      showMealPlannerCta: false,
      mealPlannerCtaLabelAr: "اختيار الوجبات",
      mealPlannerCtaLabelEn: "Choose meals",
      messageAr: "",
      messageEn: "",
      businessDate,
      pickupRequested: false,
      pickupPrepared: false,
    },
    deliverySlot: { slotId: "pickup", type: "pickup", window: "", label: "Pickup" },
    deliveryAddress: null,
    deliveryWindow: { from: "", to: "", label: "" },
    pickupLocation: { id: "main", _id: "main", name: "الفرع الرئيسي", address: "الرياض" },
    fulfillmentSummary: {
      mode: "pickup",
      title: "استلام من الفرع",
      status: "open",
      statusLabel: "مفتوح",
      message: "",
      nextAction: "select_meals",
      isEditable: true,
      isFulfillable: false,
      planningReady: true,
      fulfillmentReady: false,
      lockedReason: null,
      lockedMessage: null,
    },
    mealBalance,
  },
};

const addonChoice = {
  id: productId,
  productId,
  menuProductId: productId,
  key: "orange_juice",
  name: "Orange Juice",
  nameAr: "عصير برتقال",
  nameI18n: { ar: "عصير برتقال", en: "Orange Juice" },
  priceHalala: 500,
  priceSar: 5,
  currency: "SAR",
  calories: 110,
  prepTimeMinutes: 2,
  categoryKey: "juices",
  category: "juice",
  allowanceCategory: "juice",
  itemType: "addon",
  type: "addon",
  available: true,
  active: true,
  source: "subscription",
  isEligibleForAllowance: true,
  includedTotalQty: 10,
  remainingQty: 5,
  freeQtyAvailable: 5,
  requestedQty: 1,
  coveredQty: 1,
  paidQty: 0,
  remainingBefore: 5,
  remainingAfter: 4,
  payableTotalHalala: 0,
  unitPriceHalala: 500,
  pricingMode: "allowance_covered",
  availableForNewSale: true,
  legacyRecovered: false,
  entitlementKey: allowance.entitlementKey,
  balanceBucketId: bucketId,
  addonPlanId,
  maxPerDay: 5,
  defaultDailyQty: 1,
  walletRemainingQty: 5,
  maximumSpendableFromWallet: 5,
  ui: { selectable: true },
};

const addonChoices = {
  status: true,
  message: "ok",
  data: {
    juice: {
      groupId: addonPlanId,
      addonPlanId,
      label: "اشتراك عصير",
      labelText: "اشتراك عصير",
      addonPlanName: "اشتراك عصير",
      displayKey: "juice",
      displayCategory: "juice",
      category: "juice",
      allowanceCategory: "juice",
      entitlementCategory: "juice",
      source: "subscription",
      isPurchased: true,
      includedTotalQty: 10,
      remainingIncludedQty: 5,
      balanceBucketId: bucketId,
      sortOrder: 1,
      sourceCategories: ["juice"],
      choices: [addonChoice],
    },
  },
  addonChoiceGroups: [],
};

const builderProduct = {
  id: productId,
  key: "chicken_rice",
  type: "full_meal_product",
  name: "Chicken and Rice",
  nameI18n: { ar: "دجاج وأرز", en: "Chicken and Rice" },
  description: "",
  descriptionI18n: { ar: "", en: "" },
  imageUrl: "https://example.com/chicken.jpg",
  isVirtual: false,
  selectionType: "full_meal_product",
  itemType: "meal",
  pricingModel: "included",
  priceHalala: 0,
  currency: "SAR",
  calories: 500,
  proteinFamilyKey: "chicken",
  ui: {},
  sortOrder: 1,
  optionGroups: [],
  optionSections: [],
  action: { type: "select", requiresBuilder: false, treatAsFullMeal: true },
};

const mealPlannerMenu = {
  ok: true,
  message: "ok",
  data: {
    currency: "SAR",
    builderCatalog: {
      contractVersion: "v2",
      currency: "SAR",
      sections: [{
        id: "meals",
        key: "meals",
        type: "products",
        selectionType: "full_meal_product",
        name: "Meals",
        nameI18n: { ar: "الوجبات", en: "Meals" },
        description: "",
        ui: {},
        sortOrder: 1,
        products: [builderProduct],
      }],
      rules: {},
    },
    addons: { sections: [] },
  },
};

const mealSlot = {
  slotIndex: 1,
  slotKey: "slot_1",
  status: "complete",
  proteinId: productId,
  carbs: [{ carbId: "64c000000000000000000007", grams: 150 }],
  selectionType: "standard_meal",
  sandwichId: null,
  salad: null,
  isPremium: false,
  premiumSource: "none",
  premiumKey: null,
  premiumExtraFeeHalala: 0,
  proteinFamilyKey: "chicken",
};

const subscriptionDay = {
  ok: true,
  status: 200,
  data: {
    date: businessDate,
    status: "open",
    plannerState: "draft",
    commercialState: "ready_to_confirm",
    plannerRevisionHash: "revision-1",
    mealSlots: [mealSlot],
    addonSelections: [{
      addonId: productId,
      category: "juice",
      status: "reserved",
      source: "subscription",
      name: "عصير برتقال — اشتراك عصير",
      priceHalala: 0,
      coveredQty: 1,
      paidQty: 0,
      payableTotalHalala: 0,
      pricingMode: "allowance_covered",
      currency: "SAR",
    }],
    plannerMeta: { completeSlotCount: 1, requiredSlotCount: 1 },
    planning: { version: "v1", state: "draft", requiredMealCount: 1, selectedTotalMealCount: 1, isExactCountSatisfied: true },
    paymentRequirement: { requiresPayment: false },
    premiumExtraPayment: null,
    rules: {},
    pickupLocation: overview.data.pickupLocation,
    deliveryAddress: null,
    deliveryWindow: { from: "", to: "", label: "" },
    fulfillmentSummary: overview.data.fulfillmentSummary,
    lockedReason: null,
    lockedMessage: null,
    mealBalance,
    addonBalance: overview.data.addonBalances,
    addonSubscriptionAllowances: [allowance],
    addonCategoryAllowances: overview.data.addonCategoryAllowances,
  },
};

const pickupSlot = {
  slotId: "slot_1",
  slotKey: "slot_1",
  slotIndex: 1,
  title: { ar: "دجاج وأرز", en: "Chicken and Rice" },
  meal: { title: { ar: "دجاج وأرز", en: "Chicken and Rice" }, subtitle: { ar: "", en: "" } },
  product: { id: productId, name: { ar: "دجاج وأرز", en: "Chicken and Rice" } },
  productId,
  productName: "دجاج وأرز",
  proteinKey: "chicken",
  isAvailableForPickup: true,
  available: true,
  canSelect: true,
  pickupRequestId: null,
  reservedByPickupRequestId: null,
  status: "available",
  unavailableReason: null,
  paymentRequired: false,
  payment: { required: false, status: "not_required", amountDue: 0 },
  addons: [],
  paymentStatus: "not_required",
  amountDue: 0,
  display: {
    titleAr: "دجاج وأرز",
    titleEn: "Chicken and Rice",
    subtitleAr: "",
    subtitleEn: "",
    badgesAr: [],
    badgesEn: [],
    statusTextAr: "متاح",
    statusTextEn: "Available",
    unavailableTextAr: "",
    unavailableTextEn: "",
    selectionTextAr: "اختيار",
    selectionTextEn: "Select",
  },
};

const pickupAvailability = {
  status: true,
  data: {
    subscriptionId,
    date: businessDate,
    subscriptionDayId: dayId,
    wallet: { totalEntitlement: 52, consumedMeals: 2, reservedMeals: 2, availableMeals: 48 },
    remainingMeals: 48,
    paymentReason: null,
    plannedSlots: [pickupSlot],
    slots: [pickupSlot],
    unavailableSlots: [],
    pickupItems: [{
      itemId: "slot_1",
      itemType: "meal",
      label: "دجاج وأرز",
      selectionMode: "planned_slot",
      categoryKey: "meals",
      title: pickupSlot.title,
      subtitle: { ar: "", en: "" },
      display: pickupSlot.display,
      availability: { state: "available", available: true, canSelect: true, unavailableReason: null, reservedByPickupRequestId: null },
      payment: pickupSlot.payment,
    }],
    dayAddons: [],
    addonSummary: {},
    sections: [],
    availableSlotIds: ["slot_1"],
    unavailableSlotIds: [],
    canAppendMeals: true,
    appendLimit: 48,
    summary: {
      availableCount: 1,
      unavailableCount: 0,
      availableSelectableCount: 1,
      paymentBlockedCount: 0,
      reservedCount: 0,
      fulfilledCount: 0,
      noShowCount: 0,
      hiddenUnavailableCount: 0,
      availableMealSlotCount: 1,
      availableAddonCount: 0,
      availableSaladCount: 0,
      availableProteinExtraCount: 0,
      availableSandwichCount: 0,
      canAppendMeals: true,
      appendLimit: 48,
      titleAr: "الاستلام",
      titleEn: "Pickup",
      emptyTextAr: "",
      emptyTextEn: "",
      canCreatePickupRequest: true,
    },
  },
};

const pickupRequestData = {
  requestId,
  id: requestId,
  subscriptionId,
  subscriptionDayId: dayId,
  date: businessDate,
  mealCount: 1,
  selectedMealSlotIds: ["slot_1"],
  selectedPickupItemIds: ["slot_1"],
  selectedPickupItems: [{ itemId: "slot_1", itemType: "meal", label: "دجاج وأرز" }],
  addonCount: 0,
  itemCount: 1,
  status: "locked",
  statusLabel: "تم التأكيد",
  message: "",
  currentStep: 1,
  selectionMode: "selected_items",
  isReady: false,
  isCompleted: false,
  creditsReserved: true,
  pickupCode: "1234",
  pickupCodeIssuedAt: "2026-07-22T08:00:00.000Z",
  fulfilledAt: null,
  createdAt: "2026-07-22T08:00:00.000Z",
  idempotent: false,
  nextAction: "prepare",
  meals: [{ slotId: "slot_1", display: pickupSlot.display, title: pickupSlot.title }],
};

const pickupRequest = { status: true, data: pickupRequestData };
const pickupRequests = { status: true, data: { requests: [pickupRequestData] } };
const pickupStatus = {
  status: true,
  data: {
    subscriptionId,
    date: businessDate,
    currentStep: 1,
    status: "locked",
    statusLabel: "تم التأكيد",
    message: "",
    canModify: false,
    isReady: false,
    isCompleted: false,
    canRequestPrepare: false,
    pickupRequested: true,
    pickupPrepared: false,
    pickupCode: "1234",
    pickupCodeIssuedAt: "2026-07-22T08:00:00.000Z",
    fulfilledAt: null,
    requestBlockedReason: null,
    requestBlockedMessage: null,
    restaurantHours: { openTime: "08:00", closeTime: "23:00", isOpenNow: true },
    pickupPreparationFlowStatus: "requested",
    consumptionState: "reserved",
    fulfillmentMode: "pickup",
    pickupLocation: overview.data.pickupLocation,
  },
};

const fulfillmentStatus = {
  status: true,
  data: {
    subscriptionId,
    date: businessDate,
    deliveryMode: "pickup",
    fulfillmentModeOverride: null,
    pickupLocationIdOverride: null,
    firstDayFulfillmentOverride: false,
    status: "locked",
    statusLabel: "تم التأكيد",
    commercialState: "ready_to_prepare",
    commercialStateLabel: "جاهز للتحضير",
    consumptionState: "reserved",
    effectiveFulfillmentMode: "pickup",
    fulfillmentMode: "pickup",
    fulfillmentSummary: overview.data.fulfillmentSummary,
    pickupLocation: overview.data.pickupLocation,
    deliveryAddress: null,
    deliveryWindow: { from: "", to: "", label: "" },
    pickupCode: "1234",
    pickupCodeIssuedAt: "2026-07-22T08:00:00.000Z",
    lockedReason: null,
    lockedMessage: null,
    planningReady: true,
    fulfillmentReady: true,
    isFulfillable: false,
    canBePrepared: true,
    isTerminal: false,
    lastUpdatedAt: "2026-07-22T08:00:00.000Z",
    pollingIntervalSeconds: 10,
  },
};

const checks = [
  ["overview", contract.validateOverview, overview],
  ["addon choices", contract.validateAddonChoices, addonChoices],
  ["meal planner menu", contract.validateMealPlannerMenu, mealPlannerMenu],
  ["subscription day", contract.validateSubscriptionDay, subscriptionDay],
  ["pickup availability", contract.validatePickupAvailability, pickupAvailability],
  ["pickup request", contract.validatePickupRequest, pickupRequest],
  ["pickup request list", contract.validatePickupRequests, pickupRequests],
  ["pickup status", contract.validatePickupStatus, pickupStatus],
  ["fulfillment status", contract.validateFulfillmentStatus, fulfillmentStatus],
];

for (const [name, validate, payload] of checks) {
  assert.strictEqual(validate(payload), payload, `${name} contract should accept Flutter-compatible payload`);
}

assert.throws(
  () => contract.validatePickupAvailability({
    ...pickupAvailability,
    data: {
      ...pickupAvailability.data,
      slots: [{ ...pickupSlot, display: { ...pickupSlot.display, titleAr: undefined } }],
    },
  }),
  (error) => error && error.code === "FLUTTER_RESPONSE_CONTRACT_MISMATCH" && error.path.includes("display.titleAr")
);

assert.throws(
  () => contract.validateSubscriptionDay({
    ...subscriptionDay,
    data: { ...subscriptionDay.data, mealSlots: [{ ...mealSlot, slotKey: null }] },
  }),
  (error) => error && error.code === "FLUTTER_RESPONSE_CONTRACT_MISMATCH" && error.path.includes("slotKey")
);

console.log(`Flutter mobile response contract checks passed against ${FLUTTER_BASELINE}`);
