"use strict";

/**
 * Centralized error codes for subscription operations.
 * These codes follow the existing project pattern where errors have a `code` property.
 */

module.exports = {
  SUBSCRIPTION_NOT_ACTIVE: "SUBSCRIPTION_NOT_ACTIVE",
  SUBSCRIPTION_DATE_OUT_OF_RANGE: "SUBSCRIPTION_DATE_OUT_OF_RANGE",
  SUBSCRIPTION_DAY_LOCKED: "SUBSCRIPTION_DAY_LOCKED",
  SUBSCRIPTION_ACCESS_DENIED: "SUBSCRIPTION_ACCESS_DENIED",
  FULFILLMENT_METHOD_NOT_ALLOWED: "FULFILLMENT_METHOD_NOT_ALLOWED",
  INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
  INVALID_DATE: "INVALID_DATE",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  SUBSCRIPTION_CANCELED: "SUBSCRIPTION_CANCELED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_NOT_STARTED: "SUBSCRIPTION_NOT_STARTED",
};
